name: Run Vitest on Source (no build)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  vitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm test